<?php

namespace ContainerOxCgAki;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LSJTKbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.l_sJTKb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l_sJTKb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'etablissement' => ['privates', '.errored..service_locator.l_sJTKb.App\\Entity\\Etablissement', NULL, 'Cannot autowire service ".service_locator.l_sJTKb": it needs an instance of "App\\Entity\\Etablissement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'etablissement' => 'App\\Entity\\Etablissement',
        ]);
    }
}
