<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOSgQbIn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOSgQbIn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOSgQbIn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOSgQbIn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOSgQbIn\App_KernelDevDebugContainer([
    'container.build_hash' => 'OSgQbIn',
    'container.build_id' => 'af1138bf',
    'container.build_time' => 1695217477,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOSgQbIn');
