<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxCgAki\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxCgAki/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOxCgAki.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOxCgAki\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOxCgAki\App_KernelDevDebugContainer([
    'container.build_hash' => 'OxCgAki',
    'container.build_id' => 'e9f9ba8d',
    'container.build_time' => 1695220663,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOxCgAki');
